export const GET_LOGIN_CODE = 'GET_LOGIN_CODE';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_ALBUM_DATA = 'GET_ALBUM_DATA';
export const GET_NEW_RELEASES = 'GET_NEW_RELEASES';
